/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author 4-klambert
 */
public class calculatorpic extends javax.swing.JFrame {

    /**
     * Creates new form calculatorpic
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op; 
    public calculatorpic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnplusminus = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtndigit8 = new javax.swing.JButton();
        jbtndigit7 = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtndigit9 = new javax.swing.JButton();
        jbtndigit5 = new javax.swing.JButton();
        jbtndigit4 = new javax.swing.JButton();
        jbtnminus = new javax.swing.JButton();
        jbtndigit6 = new javax.swing.JButton();
        jbtndigit2 = new javax.swing.JButton();
        jbtndigit1 = new javax.swing.JButton();
        jbtnmultiply = new javax.swing.JButton();
        jbtndigit3 = new javax.swing.JButton();
        jbtnpoint = new javax.swing.JButton();
        jbtndigit0 = new javax.swing.JButton();
        jbtndivide = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 340, 50));

        jbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCE.setText("CE");
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 60));

        jbtnBS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBS.setText("<-");
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 60));

        jbtnplusminus.setFont(new java.awt.Font("Playbill", 1, 36)); // NOI18N
        jbtnplusminus.setText("+/-");
        jbtnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusminusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplusminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, 60));

        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, 60));

        jbtndigit8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit8.setText("8");
        jbtndigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, 60));

        jbtndigit7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit7.setText("7");
        jbtndigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 60));

        jbtnplus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnplus.setText("+");
        getContentPane().add(jbtnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 70, 60));

        jbtndigit9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit9.setText("9");
        jbtndigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 70, 60));

        jbtndigit5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit5.setText("5");
        jbtndigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 60));

        jbtndigit4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit4.setText("4");
        jbtndigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 60));

        jbtnminus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnminus.setText("-");
        getContentPane().add(jbtnminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 70, 60));

        jbtndigit6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit6.setText("6");
        jbtndigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 70, 60));

        jbtndigit2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit2.setText("2");
        jbtndigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, 60));

        jbtndigit1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit1.setText("1");
        jbtndigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 60));

        jbtnmultiply.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnmultiply.setText("*");
        getContentPane().add(jbtnmultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 70, 60));

        jbtndigit3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit3.setText("3");
        jbtndigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, 60));

        jbtnpoint.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnpoint.setText(".");
        jbtnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpointActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 70, 60));

        jbtndigit0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndigit0.setText("0");
        jbtndigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, 60));

        jbtndivide.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtndivide.setText("/");
        jbtndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivideActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 70, 60));

        jbtnequal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnequal.setText("=");
        getContentPane().add(jbtnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumbers (String q)
    {
        String Nums = jtxtResult.getText() + q;
        jtxtResult.setText(Nums);
    }
    private void jbtndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_jbtndigit4ActionPerformed

    private void jbtndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_jbtndigit5ActionPerformed

    private void jbtndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_jbtndigit6ActionPerformed

    private void jbtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtndivideActionPerformed

    private void jbtnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusminusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnplusminusActionPerformed

    private void jbtndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_jbtndigit7ActionPerformed

    private void jbtndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_jbtndigit8ActionPerformed

    private void jbtndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_jbtndigit9ActionPerformed

    private void jbtndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_jbtndigit1ActionPerformed

    private void jbtndigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_jbtndigit2ActionPerformed

    private void jbtndigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_jbtndigit3ActionPerformed

    private void jbtndigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_jbtndigit0ActionPerformed

    private void jbtnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnpointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculatorpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculatorpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculatorpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculatorpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculatorpic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtndigit0;
    private javax.swing.JButton jbtndigit1;
    private javax.swing.JButton jbtndigit2;
    private javax.swing.JButton jbtndigit3;
    private javax.swing.JButton jbtndigit4;
    private javax.swing.JButton jbtndigit5;
    private javax.swing.JButton jbtndigit6;
    private javax.swing.JButton jbtndigit7;
    private javax.swing.JButton jbtndigit8;
    private javax.swing.JButton jbtndigit9;
    private javax.swing.JButton jbtndivide;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnmultiply;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnplusminus;
    private javax.swing.JButton jbtnpoint;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
